<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfPersistenceBase\Model\AggregateRoot'                    => __DIR__ . '/src/ZfPersistenceBase/Model/AggregateRoot.php',
    'ZfPersistenceBase\Model\Repository'                       => __DIR__ . '/src/ZfPersistenceBase/Model/Repository.php',
    'ZfPersistenceBase\Infrastructure\MemoryRepository'        => __DIR__ . '/src/ZfPersistenceBase/Infrastructure/MemoryRepository.php',
    'ZfPersistenceBase\Infrastructure\MemoryRepositoryFactory' => __DIR__ . '/src/ZfPersistenceBase/Infrastructure/MemoryRepositoryFactory.php',
    'ZfPersistenceBase\Module'                                 => __DIR__ . '/src/ZfPersistenceBase/Module.php',
);