<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'GtnPersistBase\Model\RepositoryInterface'         => __DIR__ . '/src/GtnPersistBase/Model/RepositoryInterface.php',
  'GtnPersistBase\Model\AggregateRootInterface'      => __DIR__ . '/src/GtnPersistBase/Model/AggregateRootInterface.php',
  'GtnPersistBase\Infrastructure\Memory\Repository'  => __DIR__ . '/src/GtnPersistBase/Infrastructure/Memory/Repository.php',
  'GtnPersistBase\Module'                            => __DIR__ . '/src/GtnPersistBase/Module.php',
);
