<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GtnPersistBase\Model\AggregateRoot'                    => __DIR__ . '/src/GtnPersistBase/Model/AggregateRoot.php',
    'GtnPersistBase\Model\Repository'                       => __DIR__ . '/src/GtnPersistBase/Model/Repository.php',
    'GtnPersistBase\Infrastructure\MemoryRepository'        => __DIR__ . '/src/GtnPersistBase/Infrastructure/MemoryRepository.php',
    'GtnPersistBase\Module'                                 => __DIR__ . '/src/GtnPersistBase/Module.php',
);